http:
  port: 80
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/"
  auth:
    host: localhost
    paths: "/api/user/register"
  report:
    host: localhost
    paths: "/report"
serviceEndpoints:
  httpbin:
    url: "http://localhost:8081"
  httpauth:
    url: "http://localhost:3001/"
  httpreport:
    url: "http://localhost:5488/"
policies:
  - rewrite
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  default-1:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpauth
  default-2:
    apiEndpoints:
      - report
    policies:
      - rewrite:
          - condition:
              name: regexpmatch
              match: /report
            action:
              rewrite: /
      - proxy:
          - action:
              serviceEndpoint: httpreport
